- name: Create Secret
  kubernetes.core.k8s:
    namespace: "{{ namespace_name }}"
    kind: Secret
    name: "{{ secret_name }}"
    state: present
    definition:
      type: Opaque
      data:
        password: "{{ redis_password }}"