- name: Create Redis StatefulSet
  kubernetes.core.k8s:
    namespace: "{{ namespace_name }}"
    kind: StatefulSet
    name: "{{ statefulset_name }}"
    state: present
    definition:
      spec:
        serviceName: "{{ app_service_name }}"
        replicas: "{{ replica_count }}"
        selector:
          matchLabels:
            app: "{{ app_label }}"
        template:
          metadata:
            labels:
              app: "{{ app_label }}"
          spec:
            containers:
            - name: "{{ container_name }}"
              image: "{{ container_image }}"
              ports:
              - containerPort: 6379
              volumeMounts:
              - name: "{{ volume_name }}"
                mountPath: "/data"
              - name: config
                mountPath: "/usr/local/etc/redis/redis.conf"
                subPath: redis.conf
              env:
              - name: REDIS_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: "{{ secret_name }}"
                    key: password
            volumes:
            - name: config
              configMap:
                name: "{{ configmap_name }}"

        volumeClaimTemplates:
        - metadata:
            name: "{{ volume_name }}"
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "gp2"
            resources:
              requests:
                storage: "{{ storage_size }}"
